# Provider 
client_id = "<tf-client-id>"
client_secret = "<tf-client-secret>"
subscription_id = "<tf-subscription-id>"
tenant_id = "<tf-tenant-id>"
storagekey = "<tf-access-key>"
vmpassword = "<tf-default-password>"
location="EastUS"
resource_group="az-terraform-rg"
vnet="myVnet"
subnet="mySubnet"
nsg="myNetworkSecurityGroup"
vm_name="mediavm5425"
sku="Standard_DS1_v2"